server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meet1937/Microservice-Demo-Configuration
          clone-on-start: true
